version: "3"
services:
  ngweb1:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./web-server1/html:/usr/share/nginx/html
      - ./web-server1/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web-server1/nginx/cont.d:/etc/nginx/cont.d
