version: "3"
services:
  # webサーバ1（SSL）
  web-server1:
    image: nginx
    hostname: web-server1
    ports:
      - 4431:443
    volumes:
      - ./web-server1/html:/usr/share/nginx/html
      - ./web-server1/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web-server1/nginx/conf.d:/etc/nginx/conf.d
      - ./ssl/:/etc/ssl/
  # webサーバ2（80ポート）
  web-server2:
    image: nginx
    hostname: web-server2
    ports:
      - 8080:80
    volumes:
      - ./web-server2/html:/usr/share/nginx/html
      - ./web-server2/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web-server2/nginx/conf.d:/etc/nginx/conf.d
  #リバースプロキシサーバ
  reverse-proxy:
    image: nginx
    hostname: reverse-proxy
    ports:
      - 4430:443
    volumes:
      - ./reverse-proxy/html:/usr/share/nginx/html
      - ./reverse-proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/nginx/conf.d:/etc/nginx/conf.d
      - ./ssl/:/etc/ssl/
